#!/bin/sh
APPDIR=`dirname $0`;
java -Xmx768m -XstartOnFirstThread -cp "$APPDIR/src/main/java:$APPDIR/src/main/resources:$APPDIR/target/classes:/usr/local/gwt-mac-1.5.3/gwt-user.jar:/usr/local/gwt-mac-1.5.3/gwt-dev-mac.jar" com.google.gwt.dev.GWTCompiler -out "$APPDIR/target/www" "$@" dk.bregnvig.formula1.F2007;
